- hosts: kube_server  
  become: false
  remote_user: ubuntu

  vars_files: 
    - ansible-vars.yaml

  tasks:
    - name: Extract the join command
      become: true
      command: "kubeadm token create --print-join-command"
      register: join_command

    - name: show join command
      debug:
        var: join_command

    - name: Save kubeadm join_command for cluster
      local_action: copy content={{ join_command.stdout_lines | last | trim }} dest={{ join_command_location }}
      # this will default to local cwd/join_commant.out
      

